feat(github): workflows

diff --git a/.github/actions/version/action.yml b/.github/actions/version/action.yml
--- a/.github/actions/version/action.yml
+++ b/.github/actions/version/action.yml
@@ -23,7 +23,9 @@ runs:
       uses: actions/checkout@v4
       with:
         token: ${{ steps.app-token.outputs.token }}
-        branch: master
+        # TODO uncomment
+        # ref: master
+        ref: feat/sonatype-publish
 
     - name: Bump version
       shell: bash
@@ -37,17 +39,24 @@ runs:
       env:
         FILE_PATH: ./build.gradle.kts
       run: |
-        version=$(grep -o "version='[^']*'" $FILE_PATH | head -1 | cut -d"'" -f2)
+        version=$(grep -E 'version\s*=\s*"[^"]+"' $FILE_PATH | head -1 | awk -F'"' '{print $2}')
+
+        if [ -z "$version" ]; then
+          echo "Error: Failed to extract version from $FILE_PATH"
+          exit 1
+        fi
+
+        echo "Extracted version: $version"
         echo "versionName=$version" >> $GITHUB_ENV
         echo "versionName=$version" >> $GITHUB_OUTPUT
 
-    - name: Commit changes
-      id: committer
-      uses: planetscale/ghcommit-action@v0.1.44
-      env:
-        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
-      with:
-        repo: ${{ github.repository }}
-        branch: master
-        commit_message: "chore(common): version bump to ${{ steps.versionName.outputs.versionName }}"
-        file_pattern: "personalization-sdk"
+    # - name: Commit changes
+    #   id: committer
+    #   uses: planetscale/ghcommit-action@v0.1.44
+    #   env:
+    #     GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
+    #   with:
+    #     repo: ${{ github.repository }}
+    #     branch: master
+    #     commit_message: "chore(common): version bump to ${{ steps.versionName.outputs.versionName }}"
+    #     file_pattern: "personalization-sdk"
